version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: novasphere-mysql-local
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=novasphere_db
    volumes:
      - novasphere-mysql-local-data:/var/lib/mysql
    networks:
      - novasphere-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppassword']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  novasphere-network:
    driver: bridge

volumes:
  novasphere-mysql-local-data:
